Call_Logs/urls.py
from django.urls import path, include, re_path
from Call_Logs.views import callLogsView, callLogsCreateView, calllogsDetailView #, search_view

app_name = "calllogs"

urlpatterns = [
    re_path(r'^index/$', callLogsView.as_view(), name='index'),
    re_path(r'^create/$', callLogsCreateView.as_view(), name='create'),
    path('<int:pk>/', calllogsDetailView.as_view(), name='detail'),
    # re_path(r'^(?P<data>\w+)$', search_view, name='search2'),
    # path('search/<data>/', search_view, name='search'),
    # re_path(r'^update/$', update_view, name='update'),
    # re_path(r'^delete/$', delete_view, name='delete'),
]

PhoneBook/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from accounts.views import login_view
# from Call_Logs.views import search_view

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('/', login_view, name='login'),
    re_path(r'^$', login_view, name='login'),
    path('contacts/', include('book.urls')),
    path('accounts/', include('accounts.urls')),
    path('calllogs/', include('Call_Logs.urls')),
    
]

book/urls.py
from django.urls import path, include, re_path
from book.views import bookListView, bookCreateView, inline_Create_contacts, bookUpdateView

app_name = "book"

urlpatterns = [
    re_path(r'^index/$', bookListView.as_view(), name='index'),
    re_path(r'^create/$', bookCreateView.as_view(), name='create'),
    path('create2/<getNumber>/', inline_Create_contacts, name='create2'),
    path('update/<pk>/', bookUpdateView.as_view(), name='update'),
    # re_path(r'^delete/$', delete_view, name='delete'),
]

Call_Logs/models.py
from django.db import models
from django.contrib.auth.models import User
from book.models import Contacts




class call_logs(models.Model):

    callTime = models.DateTimeField(auto_now_add=True, verbose_name='Çağrı Zamanı')
    fromNumber = models.CharField(max_length=16, verbose_name='Arayan')
    toUser  = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='rn_to_user', verbose_name='Cevaplayan Kullanıcı')    
    note = models.TextField(verbose_name='Not')
    id_contacts = models.ForeignKey(Contacts, on_delete=models.SET_NULL, null= True, related_name='rn_id_contacts', verbose_name='Kayıtlı Firma')


    def __str__(self):
        return self.fromNumber

    class Meta:
        ordering = ['-callTime']

Call_Logs/forms.py
from crispy_forms.bootstrap import FormActions
from django import forms
from django.forms.models import inlineformset_factory
from crispy_forms.helper import FormHelper
from Call_Logs.models import call_logs


class CallLogsForm(forms.ModelForm):

   class Meta:
        model = call_logs
        fields = [
            # 'callTime',
            'fromNumber',
            'toUser',            
            'note',
            'id_contacts',            
        ]

class SCallLogsForm(forms.ModelForm):
    
    fromNumber = forms.CharField(label='Arayan Numara', initial='Arayan numara burası', disabled=True)  
      
    class Meta:
        model = call_logs
        fields = [
            # 'callTime',
            # 'fromNumber',           
            # 'toUser',
            'note',
            # 'id_contacts',            
        ]
    

Call_Logs/views.py
from django.shortcuts import render, Http404, HttpResponseRedirect, reverse, redirect
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DetailView
from book.models import Contacts
from book.views import bookCreateView
from Call_Logs.models import call_logs
from Call_Logs.forms import CallLogsForm, SCallLogsForm
from django.db.models import Q, When, Count, Case, BooleanField
from django.core.exceptions import ObjectDoesNotExist
import datetime



class callLogsView(ListView):
    
    model = call_logs
    template_name = 'calllogs/index.html'
    context_object_name = 'calllogs'

    
    def get_context_data(self, **kwargs):
        context = super(callLogsView, self).get_context_data(**kwargs)
        calllogs = self.get_queryset()
        return context

class callLogsCreateView(CreateView):

    model = call_logs
    form_class = CallLogsForm # form_class alanlar için widget uygulamaya yarıyor ve form_class atanırsa fields alanı olmamalı
    template_name = 'calllogs/create.html'
   
    success_url = reverse_lazy('calllogs:index')


class calllogsDetailView(DetailView):
    
    context_object_name = "callid "
    model = call_logs
    template_name = 'calllogs/detail.html'

    def detail_view(request, pk):        
        callid = call_logs.objects.get(pk=pk)
        return render(request, 'calllogs/detail.html', context={'callid':callid})

# Kullanılmıyor
# def search_view(request, data):  
    
#     getNumber = data # Kullanılmıyor 



#     try:
#         company = Contacts.objects.get(Q(phoneNumber1=data) | Q(phoneNumber2=data))
#         print(company.id)
#         companyNumbers = call_logs.objects.filter(id_contacts=company.id)
#         print(companyNumbers)
#         reqData = call_logs.objects.all()
#         caller_number = reqData.filter(id_contacts=company.id)
#         rtime = datetime.datetime.now()
#         print(caller_number)
        

#         form = SCallLogsForm(request.POST or None)
#         if form.is_valid():
#             post = form.save(commit=False)
#             user = User.objects.get(id=request.user.id)
#             post.fromNumber = data
#             post.toUser = user            
#             post.id_contacts = Contacts.objects.get(Q(phoneNumber1=data) | Q(phoneNumber2=data))          
#             form.save()
#             return HttpResponseRedirect(reverse('calllogs:index'))

#         context={
#             'rtime': rtime,
#             'data':data,
#             'getNumber':getNumber,
#             'form':form,
#             'caller_number':caller_number,
#             'company': company
#         }
#         return render(request, 'calllogs/search.html', context)
#         # Çağrı geçmişi listeler       

       
#     except Contacts.DoesNotExist:
#         context={
#             'getNumber':getNumber,
#             'data':data
#         }
#         print(context)
        
#         return HttpResponseRedirect(reverse('book:create2', kwargs={'getNumber':getNumber}))
#         # return HttpResponseRedirect(reverse('book:create2', kwargs={'getNumber':getNumber}))

       
    

    
    
#     # return HttpResponseRedirect(reverse('news-year-archive', args=(year,)))

templates/calllogs/call_logs_detail.html
{% extends 'base.html' %}
{% load  crispy_forms_tags %}

    {% block body %}    
    <h3>calllogs detail</h3>
    <p>{{callid.id}}</p>
    <p>{{callid.callTime}}</p>
    <p>{{callid.fromNumber}}</p>
    <p>{{callid.toUser}}</p>
    <p></p>
    {% endblock %}

templates/calllogs/create.html
{% extends 'base.html' %}
{%  load  crispy_forms_tags  %}

    {% block body %}

        <div class="container">
            <div class="row">
                <div class="col-md-6 mx-auto">
                     <div class="pb-2 my-4 border-bottom">
                        <h2 class="mx-5" >Yeni Kayıt Ekle</h2>
                     </div>
                    <Form method="POST" class="uniForm" enctype="multipart/form-data">
                       {% csrf_token %}
                        {{form|crispy }}
                        <input type="submit" class="btn btn-outline-primary btn-k2m mt-5 mx-3" value="Kaydet">
                        <!-- <input type="button" class="btn btn-outline-danger btn-k2m mt-5" onclick="location.href='{% url 'book:index' %}'" value="İptal"> -->
                    </form>
                </div>
            </div>

        </div>

    {% endblock %}

templates/calllogs/detail.html
{% extends 'base.html' %}
{% load  crispy_forms_tags %}

    {% block body %}    
    <h3>calllogs detail</h3>
    <p>Çağrı Numarası: {{callid.id}}</p>
    <p>Çağrı Zamanı: {{callid.callTime}}</p>
    <p>Arayan Numara: {{callid.fromNumber}}</p>
    <p>Kaydeden Kullanıcı Adı: {{callid.toUser}} | {{callid.toUser.get_full_name}}</p>
    <p>Not: {{callid.note}}</p>
    <p>Firma: {{callid.id_contacts}}</p>
    

    {% endblock %}
    


    <!-- {%  for number in caller_number %}  
    <div class="container">
        <div class="card border-primary">        
            <div class="card-header d-flex justify-content-between">
                <h5 class="mb-1"><b>Arayan Numara:</b> {{number.fromNumber}}
                    <span class="mb-2 badge badge-dark badge-pill">{{number.id}}</span>
                    <p>{{company}}</p>
                </h5>
                <h5 class="mb-1"><b>Cevaplayan Kullanıcı:</b> {{number.toUser.get_full_name}}
                    <p class="mb-2"></p>
                    <p class="mb-2"><b>Görüşme Tarihi:</b> {{number.callTime}}</p>
                </h5>                     
            </div>       
            <div class="card-body">
            <h5 class="card-title"><b>Not:</b></h5>
            <p class="card-text">{{number.note}}</p>
            
            </div>
        </div>
    </div>
{% endfor %}   -->

templates/calllogs/index.html
{% extends 'base.html' %}
{% load  crispy_forms_tags %}

    {% block body %}    
         <div id="license-index" class="container-fluid pt-5 px-5">
             <div class="row mb-3 ml-2" >
<!--                 <i class="fas fa-plus pt-2"></i>                 -->
                 <!-- <input type="button" class="btn btn-outline-primary btn-k2m" onclick="location.href={% url 'book:create' %}" value="Yeni Kayıt"> -->
             </div>
          <div class="table-responsive-sm">
            <table id="example" class="table table-hover table-fixed" style="width:100%">
                <thead class="thead-dark">
                    <tr>
                        <th>#</th>
                        <th>Kayıtlı Firma || Kişi</th> 
                        <th>Çağrı Zamanı</th>
                        <th>Arayan Numara</th>
                        <th>Cevaplayan Kullanıcı</th>                        
                        <th>Not</th>
                                               
                    </tr>
                </thead>
                <tbody>
                {% for calllog in calllogs %}
                    <tr >                        
                        <td >{{ calllog.id }}</td>
                        <td><a href="{% url 'calllogs:detail' pk=calllog.id %}">{{ calllog.id_contacts}}</a></td>
                        <td>{{ calllog.callTime }}</td>
                        <td>{{ calllog.fromNumber }}</td>
                        <td>{{ calllog.toUser.get_full_name }}</td>                        
                        <td>{{ calllog.note}}</td>
                                              
                    </tr>
                 {% endfor %}
                </tbody>
            </table>
          </div>
        </div>
    {% endblock %}

templates/calllogs/search.html
{% extends 'base.html' %}
{% load  crispy_forms_tags %}


{% block body %}  

<div class="container">
    <form method="POST" class="uniForm" enctype="multipart/form-data">{% csrf_token %} 
        <div class="card border-primary">        
            <div class="card-header d-flex justify-content-between">
              <h5 name="fromNumber" maxlength="16" required="" id="id_fromNumber">  
                <b>Arayan Numara: </b>{{data}}
                    <span class="asteriskField">*</span>
                    <span class="mb-2 badge badge-dark badge-pill">{{number.id}}</span>                                      
                    
                   <p></p> 
                <div id="div_id_id_contacts" class="form-group"> 
                    <label for="id_id_contacts" class=" requiredField">
                        <b>Kayıtlı Firma || Kişi :</b><span class="asteriskField">*</span> 
                    </label> 
                    <div class=""> 
                        <p name="id_contacts" required="" id="id_id_contacts">{{company}}</p>
                    </div> 
                </div>
                </h5>
                <h5 class="mb-1"><b>Cevaplayan Kullanıcı:</b> {{request.user.get_full_name}}
                    <p class="mb-2"></p>
                    <p class="mb-2"><b>Görüşme Tarihi:</b> {{rtime}}</p>
                </h5>                     
            </div>       
            <div class="card-body">
            <h5 class="card-title"><b>Not:</b></h5>
            <p class="card-text">{{request.note}}</p>
                <div id="div_id_note" class="form-group"> 
                    <label for="id_note" class=" requiredField">Not<span class="asteriskField">*</span> </label> 
                    <div class=""> 
                        <textarea name="note" cols="40" rows="10" class="textarea form-control" required="" id="id_note"></textarea> 
                    </div>
                </div>            
            </div>
        </div>
        <input type="submit" class="btn btn-outline-primary btn-k2m mt-5 mx-3" value="Kaydet">
    </form>
</div>


<!-- <div class="container">
        <div class="row">
            <div class="col-md-6 mx-auto">
                 <div class="pb-2 my-4 border-bottom">
                    <h2 class="mx-5" >Yeni Çağrı Kaydı Oluştur</h2>
                 </div>
                <Form method="POST" class="uniForm" enctype="multipart/form-data">
                   {% csrf_token %}    
                   {{form|crispy }}              
                                   
                    <input type="submit" class="btn btn-outline-primary btn-k2m mt-5 mx-3" value="Kaydet">                
                </form>
            </div>
        </div>
    </div>    -->
         
<hr>
  
<!-- Cards -->
{% for number in caller_number %}  
<div class="container mb-5">
    <div class="card border-primary">        
        <div class="card-header d-flex justify-content-between">
            <h5 class="mb-1"><b>Arayan Numara:</b> {{number.fromNumber}}
                 <span class="mb-2 badge badge-dark badge-pill">{{number.id}}</span>
                 <p><b>Kayıtlı Firma || Kişi :</b>   {{company}} </p>                
            </h5>
            <h5 class="mb-1"><b>Cevaplayan Kullanıcı:</b> {{number.toUser.get_full_name}}
                <p class="mb-2"></p>
                <p class="mb-2"><b>Görüşme Tarihi:</b> {{number.callTime}}</p>
            </h5>                     
        </div>       
        <div class="card-body">
          <h5 class="card-title"><b>Not:</b></h5>
          <p class="card-text">{{number.note}}</p>
          
        </div>
    </div>
</div>
{% endfor %}  


{% endblock body %}