Call_Logs/urls.py
from django.urls import path, include, re_path
from Call_Logs.views import callLogsView, callLogsCreateView, calllogsDetailView #, search_view

app_name = "calllogs"

urlpatterns = [
    re_path(r'^index/$', callLogsView.as_view(), name='index'),
    re_path(r'^create/$', callLogsCreateView.as_view(), name='create'),
    path('<int:pk>/', calllogsDetailView.as_view(), name='detail'),
    # re_path(r'^(?P<data>\w+)$', search_view, name='search2'),
    # path('search/<data>/', search_view, name='search'),
    # re_path(r'^update/$', update_view, name='update'),
    # re_path(r'^delete/$', delete_view, name='delete'),
]

PhoneBook/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from accounts.views import login_view
# from Call_Logs.views import search_view

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('/', login_view, name='login'),
    re_path(r'^$', login_view, name='login'),
    path('contacts/', include('book.urls')),
    path('accounts/', include('accounts.urls')),
    path('calllogs/', include('Call_Logs.urls')),
    
]

accounts/urls.py
from django.urls import re_path
from accounts.views import signup_view, login_view, logout_view


app_name = "accounts"

urlpatterns = [
    re_path(r'^login/$', login_view, name='login'),
    re_path(r'^logout/$', logout_view, name='logout'),
    re_path(r'^signup/$', signup_view, name='signup'),
]

book/urls.py
from django.urls import path, include, re_path
from book.views import bookListView, bookCreateView, inline_Create_contacts, bookUpdateView

app_name = "book"

urlpatterns = [
    re_path(r'^index/$', bookListView.as_view(), name='index'),
    re_path(r'^create/$', bookCreateView.as_view(), name='create'),
    path('create2/<getNumber>/', inline_Create_contacts, name='create2'),
    path('update/<pk>/', bookUpdateView.as_view(), name='update'),
    # re_path(r'^delete/$', delete_view, name='delete'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Rehber{% endblock %}</title>
<!--    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">-->
    <link rel="stylesheet" href="{% static 'css/jquery.dataTables.min.css' %}">

    <!-- Fontawesome CSS-->
    <link rel="stylesheet" href="{% static 'css/all.css' %}">

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- Custom CSS-->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">


<!--    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>-->
<!--    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>-->
<!--    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>-->

    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

</head>
<body>

    {% include "header.html" %}
    {% include 'messages.html' %}

    {% block body %}



    {% endblock %}

    {% block footer %}

    {% include 'footer.html' %}

    {% endblock footer %}


    <script>
        $(document).ready(function() {
            $('#example').DataTable();
        } );
        $(".datepicker").datepicker();

        // $(document).on('click', '.confirm-delete', function () {
        //   $("#confirmDeleteModal").attr("caller-id", $(this).attr("id"));
        // });

        // $(document).on('click', '#confirmDeleteButtonModal', function () {
        //   var caller = $("#confirmDeleteButtonModal").closest(".modal").attr("caller-id");
        //   window.location = $("#".concat(caller)).attr("href");
        // });

    </script>
</body>
</html>

templates/footer.html
<footer class="footer">
  <div class="footer-bottom ">footer</div>
</footer>

templates/header.html
<!-- Navbar Start -->
<nav class="navbar navbar-expand-lg sticky-top navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Firma Rehberi</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>
    <div class="container">
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
       {% if request.user.is_authenticated %}
        <ul class="navbar-nav mr-auto">
             <li class="nav-item dropdown"> <a class="nav-link dropdown-toggle" href="#" id="ServicesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Rehber</a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url 'book:index' %}">Rehberi Görüntüle</a>
                  <a class="dropdown-item" href="{% url 'book:create' %}">Yeni Kayıt Oluştur</a>                  
               </div>        
            </li>
            <li class="nav-item dropdown"> <a class="nav-link dropdown-toggle" href="#" id="TeknikDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Çağrı Geçmişi</a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url 'calllogs:index' %}">Çağrı Geçmişi</a>
                                                   
               </div>
            </li>
            {% if request.user.is_superuser %} 
            <li class="nav-item dropdown"> <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown2" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Admin</a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'accounts:signup' %}">Kullanıcı Ekle</a>
                    <a class="dropdown-item" href="{% url 'calllogs:create' %}">Yeni Çağrı Kaydı</a>           
               </div>
            </li>
            {% endif %}
        </ul>
        <div class="form-inline my-2 my-lg-0">
          {% if request.user.is_authenticated %}          
          <lebel class="text-k2m text-uppercase">{{request.user.get_full_name}}</lebel>
          {% endif %}
      </div>
       <lu class="navbar-nav">
            <li class="nav-item active"> <a class="nav-link" href="{% url 'accounts:logout' %}">Çıkış <span class="sr-only">(current)</span></a> </li>
       </lu>        
       {% endif %} 
      </div>
   </div>
</nav>

templates/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-success alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          {{ message }}
        </div>
    {% endfor %}
{% endif %}