PhoneBook/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from accounts.views import login_view
# from Call_Logs.views import search_view

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('/', login_view, name='login'),
    re_path(r'^$', login_view, name='login'),
    path('contacts/', include('book.urls')),
    path('accounts/', include('accounts.urls')),
    path('calllogs/', include('Call_Logs.urls')),
    
]

book/urls.py
from django.urls import path, include, re_path
from book.views import bookListView, bookCreateView, inline_Create_contacts, bookUpdateView

app_name = "book"

urlpatterns = [
    re_path(r'^index/$', bookListView.as_view(), name='index'),
    re_path(r'^create/$', bookCreateView.as_view(), name='create'),
    path('create2/<getNumber>/', inline_Create_contacts, name='create2'),
    path('update/<pk>/', bookUpdateView.as_view(), name='update'),
    # re_path(r'^delete/$', delete_view, name='delete'),
]

book/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from phone_field import PhoneField

# Create your models here.

class Contacts(models.Model):
    firstName = models.CharField(max_length=50)
    lastName = models.CharField(max_length=50)
    companyName = models.CharField(max_length=50, blank=True, null=True)
    email = models.EmailField(max_length=50, null=True, blank=True)
    phoneNumber1 = PhoneField(unique=True)
    phoneNumber2 = PhoneField(null=True, blank=True)
    address = models.TextField(max_length=254, blank=True, null=True)

    # def __str__(self):
    #     return self.firstName
           
    def __str__(self):
        if self.companyName:
            return """{} || {} {}""".format(self.companyName, self.firstName, self.lastName)
        else:  
           return """{} {}""".format(self.firstName, self.lastName)
        
        


    # def save(self, *args, **kwargs): # ilk harfı buyuten def
    #         for field_name in ['title', 'price', ... ]:
    #             val = getattr(self, field_name, False)
    #             if val:
    #                 setattr(self, field_name, val.capitalize())
    #         super(Product, self).save(*args, **kwargs)
   

    # class Caller(models.Model):
    #     author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    #     title = models.CharField(max_length=200)
    #     text = models.TextField()
    #     created_date = models.DateTimeField(default=timezone.now)
    #     published_date = models.DateTimeField(blank=True, null=True)

    # def publish(self):
    #     self.published_date = timezone.now()
    #     self.save()

    # def __str__(self):
    #     return self.title

templates/contacts/create.html
{% extends 'base.html' %}
{%  load  crispy_forms_tags  %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <div class="pb-2 my-4 border-bottom">
                <h2 class="mx-5">Yeni Müşteri Ekle</h2>
            </div>
            <Form method="POST" class="uniForm" enctype="multipart/form-data">
                {% csrf_token %}
                {{form|crispy }}
                <input type="submit" class="btn btn-outline-primary btn-k2m mt-5 mx-3" value="Kaydet">                
            </form>
        </div>
    </div>
</div>
{{data}}
{{getNumber}}
<!-- <div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <div class="pb-2 my-4 border-bottom">
                <h2 class="mx-5">Yeni Müşteri Ekle</h2>
            </div>
            <form method="POST" class="uniForm" enctype="multipart/form-data">{% csrf_token %}
                
                <div id="div_id_firstName" class="form-group"> <label for="id_firstName" class=" requiredField">
                        Adı<span class="asteriskField">*</span> </label>
                    <div class=""> <input type="text" name="firstName" class="textinput textInput form-control"
                            required="" id="id_firstName"> </div>
                </div>
                <div id="div_id_lastName" class="form-group"> <label for="id_lastName" class=" requiredField">
                        Soyadı<span class="asteriskField">*</span> </label>
                    <div class=""> <input type="text" name="lastName" class="textinput textInput form-control"
                            required="" id="id_lastName"> </div>
                </div>
                <div id="div_id_companyName" class="form-group"> <label for="id_companyName" class="">
                        Firma Adı
                    </label>
                    <div class=""> <input type="text" name="companyName" class="textinput textInput form-control"
                            id="id_companyName"> </div>
                </div>
                <div id="div_id_email" class="form-group"> <label for="id_email" class="">
                        E-Posta
                    </label>
                    <div class=""> <input type="email" name="email" class="emailinput form-control" id="id_email">
                    </div>
                </div>
                <div id="div_id_phoneNumber1" class="form-group">
                    <label for="id_phoneNumber1" class=" requiredField">
                        1. Telefon Numarası<span class="asteriskField">*</span>
                    </label>
                    <div class="">
                         <input type="text" name="phoneNumber1" value="{{data}}" class="textinput textInput form-control"
                            required="" id="id_phoneNumber1">
                    </div>
                </div>
                <div id="div_id_phoneNumber2" class="form-group"> <label for="id_phoneNumber2" class="">
                        2. Telefon Numarası
                    </label>
                    <div class=""> <input type="text" name="phoneNumber2" class="textinput textInput form-control"
                            id="id_phoneNumber2"> </div>
                </div>
                <div id="div_id_address" class="form-group"> <label for="id_address" class="">
                        Adres:
                    </label>
                    <div class=""> <input type="text" name="address" class="textinput textInput form-control"
                            id="id_address"> </div>
                </div>
                <input type="submit" class="btn btn-outline-primary btn-k2m mt-5 mx-3" value="Kaydet">                
            </form>
        </div>
    </div>
</div> -->

{% endblock %}

templates/contacts/index.html
{% extends 'base.html' %}
{% load  crispy_forms_tags %}

    {% block body %}    
         <div id="license-index" class="container-fluid pt-5 px-5">
             <div class="row mb-3 ml-2" >
<!--                 <i class="fas fa-plus pt-2"></i>                 -->
                 <!-- <input type="button" class="btn btn-outline-primary btn-k2m" onclick="location.href={% url 'book:create' %}" value="Yeni Kayıt"> -->
             </div>
          <div class="table-responsive-sm">
            <table id="example" class="table table-hover table-fixed" style="width:100%">
                <thead class="thead-dark">
                    <tr>
                        <th>Adı</th>
                        <th>Soyadı</th>
                        <th>Firma Adı</th>
                        <th>E-Posta</th>
                        <th>Telefon Numarası 1</th>
                        <th>Telefon Numarası 2</th>
                        <th>Adres</th>                        
                    </tr>
                </thead>
                <tbody>
                {% for contact in contacts %}
                    <tr >                        
                        <td ><a href="{% url 'book:update' pk=contact.id %}">{{ contact.firstName }}</a></td>
                        <td>{{ contact.lastName }}</td>
                        <td>{{ contact.companyName }}</td>
                        <td>{{ contact.email }}</td>
                        <td>{{ contact.phoneNumber1 }}</td>
                        <td>{{ contact.phoneNumber2}}</td>
                        <td>{{ contact.address}}</td>                      
                    </tr>
                 {% endfor %}
                </tbody>
            </table>
          </div>
        </div>      
        
           
    {% endblock %}

templates/contacts/update.html
{% extends 'base.html' %}
{%  load  crispy_forms_tags  %}

    {% block body %}

        <div class="container">
            <div class="row">
                <div class="col-md-6 mx-auto">
                     <div class="pb-2 my-4 border-bottom">
                        <h2 class="mx-5" >Güncelle</h2>
                     </div>
                    <Form method="POST" class="uniForm" enctype="multipart/form-data">
                       {% csrf_token %}
                        {{form|crispy }}
                        <input type="submit" class="btn btn-outline-primary btn-k2m mt-5 mx-3" value="Güncelle">
                        <a href="{% url 'book:index' %}" class="btn btn-danger btn-k2m mt-5 mx-3" role="button">İptal</a>              
                        
                    </form>
                </div>
            </div>

        </div>

    {% endblock %}